Make tests optional and require c++ stdlib 11
ufo-kit/ufo-core pull request #183
Opened 2022-05-09 07:44 UTC by MarcusZuber

Fixes https://github.com/ufo-kit/ufo-core/issues/181

2022-05-09 07:45 UTC, MarcusZuber commented
@tfarago Could you have a look at the meson configs? Could this be done better?

2022-05-09 12:01 UTC, tfarago commented
Maybe [compiler-options](https://mesonbuild.com/Builtin-options.html#compiler-options) instead of `override_options`? I didn't even find it in the docs, where is it documented?

2022-05-09 21:14 UTC, eli-schwartz commented
https://mesonbuild.com/Reference-manual_functions.html#executable

> override_options: takes an array of strings in the same format as `project`'s `default_options` overriding the values of these options for this target only.

2022-05-09 21:15 UTC, eli-schwartz requested changes

2022-05-09 21:15 UTC, eli-schwartz commented on tests/unit/meson.build
> +        override_options : ['c++_std=c++11']
```suggestion
        override_options : ['cpp_std=c++11']
```

2022-05-09 21:17 UTC, eli-schwartz commented
BTW is there any reason you need to exclude the testsuite? You could just not run it.

Even when used as a subproject, you can use the `--suite` option to `meson test` to only run the tests for the main project, but not subprojects.

2022-05-10 04:05 UTC, MarcusZuber commented on tests/unit/meson.build
> +        override_options : ['c++_std=c++11']
Oh, you are right. I will fix this.

2022-05-10 04:07 UTC, MarcusZuber commented
> https://mesonbuild.com/Reference-manual_functions.html#executable
> 
> > override_options: takes an array of strings in the same format as `project`'s `default_options` overriding the values of these options for this target only.

Correct. I wanted that this would not interfere with potential other requested versions in other targets.

2022-05-10 04:12 UTC, MarcusZuber commented
> BTW is there any reason you need to exclude the testsuite? You could just not run it.
> 
> Even when used as a subproject, you can use the `--suite` option to `meson test` to only run the tests for the main project, but not subprojects.

The idea behind it was, that you can compile the rest, even when meson does not find a c++ compiler implementing the requested version.

I'm not sure if meson just adds only the compiler option or if it checks something. On the machines I had to hand all version where available that meson allows to set, so I could not test it.

2022-05-10 06:45 UTC, tfarago approved these changes

2022-05-11 06:20 UTC, merged